# Generated by Django 4.2 on 2023-05-03 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64)),
                ('num', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=16)),
                ('fantasy_name', models.CharField(max_length=64)),
                ('social_reason', models.CharField(max_length=64)),
                ('id_user_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_contract', models.DateField()),
                ('pis', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='employee_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_position', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_oab', models.CharField(max_length=32)),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.employee')),
            ],
        ),
        migrations.CreateModel(
            name='legal_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_process', models.CharField(max_length=64)),
                ('process_type', models.CharField(max_length=32)),
                ('register_time', models.DateTimeField(auto_now=True)),
                ('id_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.client')),
                ('id_lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(max_length=32)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='user_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=32)),
                ('user_pwd', models.CharField(max_length=64)),
                ('id_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.address')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id_legal_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.legal_process')),
            ],
        ),
        migrations.CreateModel(
            name='physical_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=10)),
                ('date_birth', models.DateField()),
                ('given_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('id_user_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='id_physical_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.physical_person'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.employee_position'),
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=128)),
                ('update_time', models.TimeField(auto_now=True)),
                ('id_legal_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.legal_process')),
            ],
        ),
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateField()),
                ('register_time', models.DateTimeField(auto_now=True)),
                ('id_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.client')),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.employee')),
                ('id_lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='connect_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=12)),
                ('connect_time', models.DateTimeField(auto_now=True)),
                ('id_user_tbl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('id_states', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.states')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='id_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.city'),
        ),
    ]
