# Generated by Django 4.2 on 2023-05-03 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silveiraAdvog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_user_tbl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.user_tbl'),
        ),
        migrations.AlterField(
            model_name='connect_reg',
            name='id_user_tbl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.user_tbl'),
        ),
        migrations.AlterField(
            model_name='physical_person',
            name='id_user_tbl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silveiraAdvog.user_tbl'),
        ),
    ]
